# Generated by Django 4.2.10 on 2024-06-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/embed/ji7J3GwhfdU?si=aGjz83D0b7bqvMQj', null=True),
        ),
    ]
